install:
	# this works
	echo "y" | sudo apt-get install dnsutils
	# this doesn't work; we get error:
	# sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	sudo apt-get -y install dnsutils
