.PHONY: phony1 phony2

phony1:
	@echo "phony1"
	echo phony1 > phony1

phony2:
	@echo "phony2"
	echo phony2 > phony2

.PHONY: phony3
phony3:
	@echo "phony3"
	echo phony3 > phony3

real:
	@echo "real"
	echo real > real
