version: "3"
services:
  mysql:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=DUM8L3DOR3"
    ports:
      - "3306:3306"
    volumes:
      - "mysqldb:/var/lib/mysql"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server # --appendonly yes
volumes:
  mysqldb: {}
  mongodb: {}
# networks:
#   hive:
