version: "3"
services:
  worker:
    image: ozydingo/busybee
    environment:
      - "redis_host=redis://redis:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - hive
  redis:
    image: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - "/home/docker/data:/data"
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]
    command: redis-server # --appendonly yes
    networks:
      - hive
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   networks:
  #     - hive
networks:
  hive:
