version: "3"
services:
  web:
    image: ozydingo/workers-web:latest
    environment:
      - AM_I_DOCKER=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
  worker:
    image: ozydingo/workers-worker:latest
    environment:
      - AM_I_DOCKER=true
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server # --appendonly yes
    networks:
      - webnet
  rq_dashboard:
    image: eoranged/rq-dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    ports:
      - "9181:9181"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
