FROM python:3.7-slim
WORKDIR /service
ENV NAME web
EXPOSE 80

COPY ./web web
COPY ./worker/lib lib
ENV PYTHONPATH /service/lib

RUN pip install --trusted-host pypi.python.org -r web/requirements.txt

CMD ["python", "-u", "web/app/app.py"]
