FROM python:3.7-slim
WORKDIR /service
ENV NAME worker

COPY ./worker worker
ENV PYTHONPATH /service/worker/lib

RUN pip install --trusted-host pypi.python.org -r worker/requirements.txt

CMD ["rq", "worker", "--url", "redis://redis"]
